### ISSUE TITLE
workspace-d-installer.exe exits immediately after its executed in any way other than through dub

### ISSUE THREAD

**Issue by poliklosio** [Pure-D/workspace-d-installer#4] opened 2016-04-10 22:54 UTC
Whether I open it in cmd or through double click, it opens in separate console window.
Then, it finishes and kills the console window, taking any displayed messages, like errors, with it.
Only running with dub allows actually reading any error messages.
System: Win 7, 64 bit

**Comment by Vild** [comment] 2016-04-11 04:43
Duplicate of #3, please continue this issue in that thread.

**Closed by Vild** 2016-04-11 04:43 UTC

**Comment by poliklosio** [comment] 2016-04-11 06:27
I respectfully disagree that this is a duplicate of issue #3.
I have wasted considerable time under assumption that the run was successful (It wasn't) precisely because I couldn't see the error message. Please, note that a new user does not necessarily know what is the expected behavior, unless an example is shown in the documentation.

**Comment by WebFreak001** [comment] 2016-04-11 18:00
If it stops instantly it should also stop instantly when it finishes compiling with dub. Dub only runs the program in the console for you
