### ISSUE TITLE
/usr/bin/ld: cannot find -lcurl

### ISSUE THREAD

**Issue by llaine** [Pure-D/workspace-d-installer#7] opened 2016-05-24 07:59 UTC
Hi,

After several try to install the package it always crashes with the same error. 

```
Performing "release" build using dmd for x86_64.
dub 0.9.25: target for configuration "library" is up to date.
dunit 1.0.12: target for configuration "library" is up to date.
painlesstraits 0.2.0: target for configuration "library" is up to date.
painlessjson 1.3.7: target for configuration "library" is up to date.
workspace-d 2.7.1+commit.3.g3b20935: building configuration "application"...
../../.dub/packages/dub-0.9.25/dub/source/dub/internal/vibecompat/core/file.d(20,15): Deprecation: module std.stream is deprecated - It will be removed from Phobos in October 2016. If you still need it, go to https://github.com/DigitalMars/undeaD
../../.dub/packages/dub-0.9.25/dub/source/dub/internal/sdlang/lexer.d(16,8): Deprecation: module std.stream is deprecated - It will be removed from Phobos in October 2016. If you still need it, go to https://github.com/DigitalMars/undeaD
source/app.d(144,29): Deprecation: workspaced.com.dub.object is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dub.core is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dub.std is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dub.painlessjson is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dub.workspaced is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dub.dub is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dub.BuildIssue is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dub.DubPackageInfo is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dcd.object is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dcd.std is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dcd.core is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dcd.painlessjson is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dcd.workspaced is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dcd.DCDServerStatus is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dcd.DCDIdentifier is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dcd.DCDSearchResult is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dfmt.object is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dfmt.std is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dfmt.core is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dfmt.painlessjson is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dfmt.workspaced is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dscanner.object is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dscanner.std is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dscanner.core is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dscanner.painlessjson is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dscanner.workspaced is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dscanner.DScannerIssue is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dscanner.OutlineTreeNode is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dscanner.DefinitionElement is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dlangui.object is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dlangui.std is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dlangui.core is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dlangui.painlessjson is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dlangui.workspaced is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dlangui.LocationType is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.dlangui.LocationInfo is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.fsworkspace.object is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.fsworkspace.std is not visible from module app
source/app.d(144,29): Deprecation: workspaced.com.fsworkspace.workspaced is not visible from module app
Linking...
/usr/bin/ld: cannot find -lcurl
collect2: erreur : ld a retourné 1 code d'état d'exécution
--- errorlevel 1
dmd failed with exit code 1.
```

DMd version : 2.071.0
Dub version : 0.9.25

**Comment by Vild** [comment] 2016-05-24 09:59
Duplicate of https://github.com/Pure-D/workspace-d/issues/16

**Closed by Vild** 2016-05-24 09:59 UTC
Labels: duplicate
